### ISSUE TITLE
你好，运行code的报错，module!=nullptr

### ISSUE THREAD

**Issue by wangbq18** [cdj0311/keras_bert_classification#1]
F tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:847 check failed:module!=nullptr,
请问这个您遇到过吗?

**Comment by cdj0311** [comment]
> F tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:847 check failed:module!=nullptr,
> 请问这个您遇到过吗?
没有遇到过，是cuda没有安装正确吗？

**Comment by wangbq18** [comment]
> 
> 
> > F tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:847 check failed:module!=nullptr,
> > 请问这个您遇到过吗?
> > 没有遇到过，是cuda没有安装正确吗？

cuda安装应该没问题，其他模型都可以正常使用GPU训练

**Comment by wangbq18** [comment]
> 
> 
> > F tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:847 check failed:module!=nullptr,
> > 请问这个您遇到过吗?
> > 没有遇到过，是cuda没有安装正确吗？

请问您的keras和tf都是什么版本

**Comment by cdj0311** [comment]
> > > F tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:847 check failed:module!=nullptr,
> > > 请问这个您遇到过吗?
> > > 没有遇到过，是cuda没有安装正确吗？
> 
> 请问您的keras和tf都是什么版本

tf1.12 + keras2.2.4

**Comment by wangbq18** [comment]
> > > > F tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:847 check failed:module!=nullptr,
> > > > 请问这个您遇到过吗?
> > > > 没有遇到过，是cuda没有安装正确吗？
> > 
> > 
> > 请问您的keras和tf都是什么版本
> 
> tf1.12 + keras2.2.4
多谢

**Comment by wangbq18** [comment]
> 
> 
> > > > > F tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:847 check failed:module!=nullptr,
> > > > > 请问这个您遇到过吗?
> > > > > 没有遇到过，是cuda没有安装正确吗？
> > > 
> > > 
> > > 请问您的keras和tf都是什么版本
> > 
> > 
> > tf1.12 + keras2.2.4
> > 多谢

> 
> 
> > > > F tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:847 check failed:module!=nullptr,
> > > > 请问这个您遇到过吗?
> > > > 没有遇到过，是cuda没有安装正确吗？
> > 
> > 
> > 请问您的keras和tf都是什么版本
> 
> tf1.12 + keras2.2.4

不好意思，后面又遇到问题了，训练到124/3126[>................] 报错 valueError: Error when checking target:expect dense_2 to have shape(2,) have(2,) but got array with shape(1,)

**Comment by cdj0311** [comment]
> > > > > > F tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:847 check failed:module!=nullptr,
> > > > > > 请问这个您遇到过吗?
> > > > > > 没有遇到过，是cuda没有安装正确吗？
> > > > 
> > > > 
> > > > 请问您的keras和tf都是什么版本
> > > 
> > > 
> > > tf1.12 + keras2.2.4
> > > 多谢
> 
> > > > > F tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:847 check failed:module!=nullptr,
> > > > > 请问这个您遇到过吗?
> > > > > 没有遇到过，是cuda没有安装正确吗？
> > > 
> > > 
> > > 请问您的keras和tf都是什么版本
> > 
> > 
> > tf1.12 + keras2.2.4
> 
> 不好意思，后面又遇到问题了，训练到124/3126[>................] 报错 valueError: Error when checking target:expect dense_2 to have shape(2,) have(2,) but got array with shape(1,)

重新更新了代码，你再试试

**Comment by wangbq18** [comment]
> 
> 
> > > > > > > F tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:847 check failed:module!=nullptr,
> > > > > > > 请问这个您遇到过吗?
> > > > > > > 没有遇到过，是cuda没有安装正确吗？
> > > > > 
> > > > > 
> > > > > 请问您的keras和tf都是什么版本
> > > > 
> > > > 
> > > > tf1.12 + keras2.2.4
> > > > 多谢
> > 
> > 
> > > > > > F tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:847 check failed:module!=nullptr,
> > > > > > 请问这个您遇到过吗?
> > > > > > 没有遇到过，是cuda没有安装正确吗？
> > > > 
> > > > 
> > > > 请问您的keras和tf都是什么版本
> > > 
> > > 
> > > tf1.12 + keras2.2.4
> > 
> > 
> > 不好意思，后面又遇到问题了，训练到124/3126[>................] 报错 valueError: Error when checking target:expect dense_2 to have shape(2,) have(2,) but got array with shape(1,)
> 
> 重新更新了代码，你再试试

非常感谢，我找到原因了，问题处在对标签数据的处理上，我改成y = keras.utils.to_categorical(y, num_classes)，就能正常运行了

**Comment by taichuai** [comment]
你好，请问你的 module!=nullptr 是怎么解决的，能请教一下吗？

**Comment by taichuai** [comment]
> F tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:847 check failed:module!=nullptr,
> 请问这个您遇到过吗?

你好，请问你的 module!=nullptr 是怎么解决的，能请教一下吗？

**Comment by cdj0311** [comment]
> > F tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:847 check failed:module!=nullptr,
> > 请问这个您遇到过吗?
> 
> 你好，请问你的 module!=nullptr 是怎么解决的，能请教一下吗？

GPU内存被别的程序占满了

**Comment by taichuai** [comment]
多谢！解决了
