### ISSUE TITLE
GPU训练

### ISSUE THREAD

**Issue by taichuai** [cdj0311/keras_bert_classification#2]
您好，请问想使用ＧＰＵ训练，参数怎么修改，我改动过import_tf 中的参数，但是仍然不行

**Comment by cdj0311** [comment]
> 您好，请问想使用ＧＰＵ训练，参数怎么修改，我改动过import_tf 中的参数，但是仍然不行

如果GPU和CUDA装好了默认就会使用GPU训练

**Comment by taichuai** [comment]
额，试了好像不行，还是在用CPU在训练，所以过程会比较慢
