### ISSUE TITLE
您好，对这个方法encode(self, sentence)不是很理解

### ISSUE THREAD

**Issue by yangchangli** [cdj0311/keras_bert_classification#3]
您好，这个方法encode(self, sentence)是如何将对应的文本转换成此对应的词向量的？是如何变化的呢？
我理解的是这个方法只是简单的将这个文本放入队列，然后再取出来，这期间没有发生变化的呀
def encode(self, sentence):
        self.input_queue.put(sentence)
        prediction = self.output_queue.get()
        return prediction

**Comment by cxfhjlhwxpd** [comment]
我也不理解，你现在理解了吗？
