### ISSUE TITLE
关于Bert+DSSM

### ISSUE THREAD

**Issue by wanghao07456** [cdj0311/keras_bert_classification#5]
请问有关于BERT+DSSM的代码吗

**Comment by cdj0311** [comment]
> 请问有关于BERT+DSSM的代码吗

有代码，但是效果还不是很好就没有放出来

**Comment by hanghr** [comment]
bert+dssm不如原生的dssm么？

**Comment by wanghao07456** [comment]
> > 请问有关于BERT+DSSM的代码吗
> 
> 有代码，但是效果还不是很好就没有放出来

你好，方便放出来交流学习下吗？

**Comment by cdj0311** [comment]
> > > 请问有关于BERT+DSSM的代码吗
> > 
> > 
> > 有代码，但是效果还不是很好就没有放出来
> 
> 你好，方便放出来交流学习下吗？

可以的，就这两天吧
